'use client'

import { jsPDF } from 'jspdf'
import { formatDate, formatCurrency } from '@/lib/utils'

interface TicketPDFData {
    ticketId: string
    eventTitle: string
    eventDate: string
    eventLocation: string
    ticketType: string
    qrCodeDataUrl: string | null
}

interface OrderPDFData {
    orderId: string
    eventTitle: string
    eventDate: string
    eventLocation: string
    tickets: Array<{
        id: string
        ticketType: string
        qrCodeDataUrl: string | null
    }>
    subtotal: number
    serviceFee: number
    total: number
    orderDate: string
}

// Generate a ticket PDF
export async function generateTicketPDF(data: TicketPDFData): Promise<void> {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    })

    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const contentWidth = pageWidth - margin * 2

    // Header background
    doc.setFillColor(124, 58, 237) // violet-600
    doc.rect(0, 0, pageWidth, 50, 'F')

    // Logo/Title
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(24)
    doc.setFont('helvetica', 'bold')
    doc.text('🎟️ EventHub', margin, 25)

    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.text('Your Event Ticket', margin, 35)

    // Event title
    doc.setTextColor(30, 41, 59) // slate-800
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text(data.eventTitle, margin, 70)

    // Ticket type badge
    doc.setFillColor(243, 232, 255) // violet-100
    doc.roundedRect(margin, 78, 60, 8, 2, 2, 'F')
    doc.setFontSize(10)
    doc.setTextColor(124, 58, 237) // violet-600
    doc.text(data.ticketType, margin + 5, 84)

    // Event details
    doc.setTextColor(71, 85, 105) // slate-600
    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')

    let y = 100
    doc.text(`📅  ${data.eventDate}`, margin, y)
    y += 10
    doc.text(`📍  ${data.eventLocation}`, margin, y)
    y += 10
    doc.text(`🎫  Ticket ID: ${data.ticketId.slice(0, 8)}...`, margin, y)

    // QR Code section
    y += 25
    doc.setFillColor(248, 250, 252) // slate-50
    doc.roundedRect(margin, y, contentWidth, 90, 4, 4, 'F')

    doc.setDrawColor(226, 232, 240) // slate-200
    doc.setLineWidth(0.5)
    doc.roundedRect(margin, y, contentWidth, 90, 4, 4, 'S')

    // QR Code
    if (data.qrCodeDataUrl) {
        const qrSize = 60
        const qrX = (pageWidth - qrSize) / 2
        doc.addImage(data.qrCodeDataUrl, 'PNG', qrX, y + 10, qrSize, qrSize)
    }

    doc.setTextColor(100, 116, 139) // slate-500
    doc.setFontSize(10)
    doc.text('Show this QR code at the event entrance', pageWidth / 2, y + 80, { align: 'center' })

    // Footer
    const footerY = 270
    doc.setFillColor(248, 250, 252) // slate-50
    doc.rect(0, footerY, pageWidth, 30, 'F')

    doc.setTextColor(148, 163, 184) // slate-400
    doc.setFontSize(8)
    doc.text(`Generated by EventHub • ${new Date().toLocaleDateString()}`, pageWidth / 2, footerY + 10, { align: 'center' })
    doc.text('This ticket is non-transferable. Please bring a valid ID.', pageWidth / 2, footerY + 16, { align: 'center' })

    // Save
    doc.save(`ticket-${data.ticketId.slice(0, 8)}.pdf`)
}

// Generate order confirmation PDF with all tickets
export async function generateOrderPDF(data: OrderPDFData): Promise<void> {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    })

    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const contentWidth = pageWidth - margin * 2

    // Header background
    doc.setFillColor(16, 185, 129) // emerald-500
    doc.rect(0, 0, pageWidth, 50, 'F')

    // Logo/Title
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(24)
    doc.setFont('helvetica', 'bold')
    doc.text('✅ Order Confirmed', margin, 25)

    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.text(`Order #${data.orderId.slice(0, 8)}`, margin, 35)

    // Event title
    doc.setTextColor(30, 41, 59) // slate-800
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text(data.eventTitle, margin, 65)

    // Event details
    doc.setTextColor(71, 85, 105) // slate-600
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')

    let y = 80
    doc.text(`📅  ${data.eventDate}`, margin, y)
    y += 8
    doc.text(`📍  ${data.eventLocation}`, margin, y)

    // Order summary box
    y += 20
    doc.setFillColor(248, 250, 252) // slate-50
    doc.roundedRect(margin, y, contentWidth, 50, 4, 4, 'F')
    doc.setDrawColor(226, 232, 240) // slate-200
    doc.roundedRect(margin, y, contentWidth, 50, 4, 4, 'S')

    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 41, 59)
    doc.text('Order Summary', margin + 5, y + 10)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(71, 85, 105)

    const col1 = margin + 5
    const col2 = margin + contentWidth - 5

    y += 20
    doc.text('Subtotal', col1, y)
    doc.text(formatCurrency(data.subtotal), col2, y, { align: 'right' })

    y += 8
    doc.text('Service Fee', col1, y)
    doc.text(formatCurrency(data.serviceFee), col2, y, { align: 'right' })

    y += 8
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 41, 59)
    doc.text('Total Paid', col1, y)
    doc.text(formatCurrency(data.total), col2, y, { align: 'right' })

    // Tickets section
    y += 25
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(`Your Tickets (${data.tickets.length})`, margin, y)

    // Draw each ticket with QR
    for (let i = 0; i < data.tickets.length; i++) {
        const ticket = data.tickets[i]
        y += 15

        // Check if we need a new page
        if (y > 240) {
            doc.addPage()
            y = 30
        }

        doc.setFillColor(255, 255, 255)
        doc.roundedRect(margin, y, contentWidth, 35, 4, 4, 'F')
        doc.setDrawColor(226, 232, 240)
        doc.roundedRect(margin, y, contentWidth, 35, 4, 4, 'S')

        // Ticket info
        doc.setFontSize(11)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(30, 41, 59)
        doc.text(`Ticket #${i + 1}`, margin + 5, y + 12)

        doc.setFont('helvetica', 'normal')
        doc.setFontSize(10)
        doc.setTextColor(71, 85, 105)
        doc.text(ticket.ticketType, margin + 5, y + 20)
        doc.text(`ID: ${ticket.id.slice(0, 8)}...`, margin + 5, y + 28)

        // QR code
        if (ticket.qrCodeDataUrl) {
            doc.addImage(ticket.qrCodeDataUrl, 'PNG', margin + contentWidth - 35, y + 2.5, 30, 30)
        }

        y += 35
    }

    // Footer
    const footerY = 270
    doc.setFillColor(248, 250, 252)
    doc.rect(0, footerY, pageWidth, 30, 'F')

    doc.setTextColor(148, 163, 184)
    doc.setFontSize(8)
    doc.text(`Generated by EventHub • Order placed: ${data.orderDate}`, pageWidth / 2, footerY + 10, { align: 'center' })
    doc.text('Keep this document safe. Show QR codes at the event entrance.', pageWidth / 2, footerY + 16, { align: 'center' })

    // Save
    doc.save(`order-${data.orderId.slice(0, 8)}.pdf`)
}
